apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: tempo
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceqlSearch:
        enabled: true
      tracesToMetrics:
        datasourceUid: tempo
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
